# This program illustrates usuage of various python built-in data types.
#Getting the data type:
#Using type() function you can get data type of any object
x=5
print(x)
print(type(x))
# Setting the data type by declaring variables
x=55
print(x)
print(type(x))
y="Hello World"
print(y)
print(type(y))
z= 55.55
print(z)
print(type(z))
a=1j
print(a)
print(type(a))
b = ["apple","banana","orange"]
print(b)
print(type(b))
c=("Pineapple","Grapes","Mango")
print(c)
print(type(c))
d=range(10,0,1)
print(d)
print(type(d))
e = {"name":"TestCase 1","Status": "Pass"}
print(e)
print(type(e))
cars = {"Hatchback","SUVs","MUVs"}
print(cars)
print(type(cars))
Bikes = frozenset({"Street","Adventure","Touring"})
print(Bikes)
print(type(Bikes))
Check=True
print(Check)
print(type(Check))
Size = b"Hello"
print(Size)
print(type(Size))
x=bytearray(5)
print(x)
print(type(x))
r=memoryview(bytes(5))
print(r)
print(type(r))
Q = None
print(Q)
print(type(Q))
# Setting the specific data type while declaring variables
x= str("Hello World")
print(x)
print(type(x))
x= int(5)
print(x)
print(type(x))
x = float(3.4)
print(x)
print(type(x))
x= complex(1j)
print(x)
print(type(x))
Flavour = list(("Vannila","Strawberry","Chocolate"))
print(Flavour)
print(type(Flavour))
Tree = tuple(("Neem","Banana","Mango"))
print(Tree)
print(type(Tree))
x=range(6)
print(x)
print(type(x))
x=dict(name="Kumar",Age=40)
print(x)
print(type(x))
x=set(("apple","banana","cherry"))
print(x)
print(type(x))
x=frozenset(("orange","pineapple","kiwi"))
print(x)
print(type(x))
x=bool(5)
print(x)
print(type(x))
x= bytes(5)
print(x)
print(type(x))
x= bytearray(5)
print(x)
print(type(x))
x= memoryview(bytes(5))
print(x)
print(type(x))
x= None
print(x)
print(type(x))
