print('Hello, World!')
print("Hello, This is a test print statement.")
print('This is a test ',end="")
print('for learning python ',end="")
print('and practicing print statements.')
print(3)
print(3*5)
print("Sum of 3 and 5 is:", 3+5)
print('Multiply 3 and 5 is:'+ str(3*5))
print("Division of 10 by 2 is:", str(10/2))
print("I am",35,"Years old.")
print("The Movie starts at",7,"PM.")
print(type(3))